- Classes/Object Explorers/FLEXObjectExplorerViewController.m
This pull request adds a commit that allows users of FLEX to long press on description rows and copy their contents. This was done to resolve [this issue](https://github.com/Flipboard/FLEX/issues/38). It should be extensible to copying other rows too if that's ever desired.
> Copy object description

- Classes/Editing/Argument Input Views/FLEXArgumentInputDateView.h
- Classes/Editing/Argument Input Views/FLEXArgumentInputDateView.m
- Classes/Editing/Argument Input Views/FLEXArgumentInputViewFactory.h
- Classes/Editing/Argument Input Views/FLEXArgumentInputViewFactory.m
- Classes/Editing/FLEXDefaultEditorViewController.m
- Example/UICatalog.xcodeproj/project.pbxproj
The argument input for dates is an UIDatePicker, set to use gregorian
calendar and UTC time zone (the locale is still the current one).
Unfortunately UIDatePicker doesn’t give an option for showing seconds.
Works in the object explorer and the defaults explorer. The changes
around ArgumentInputViewFactory and DefaultEditorVC allows to introspect
the value for its class and show the right editor (otherwise the JSON
editor is used by default).
> Add editor for NSDate values.

- Classes/Explorer Toolbar/FLEXManager.h
- Classes/Explorer Toolbar/FLEXManager.m
- Example/UICatalog/AAPLCatalogTableTableViewController.m
Makes possible to provide custom UIViewController for user defined global entry, which will be pushed on to the FLEX manager's navigation view controller stack instead of explorer view controller. This could be used to add some custom UI for testers, add different switches/notes, for example network stubbing could be toggled from such custom UI.
> Added ability to add UIViewController based user defined global entries.

- Classes/Network/PonyDebugger/FLEXNetworkObserver.m
Completion handler may be expecting fileURL so should always pass through the response that the session task gave us.
> Fix fileURLOrData passthrough in network observer

- Classes/Network/FLEXNetworkTransactionDetailTableViewController.m
- Classes/Utility/FLEXUtility.h
- Classes/Utility/FLEXUtility.m
Hello @ryanolsonk,
in some of my case, server return the wrong mime type like "text/html" for json data. I think it will be better using a method `isValidJSONData:` to check it. `prettyJSONStringFromData:` handle only the real json data. how do you feel? thank you.
> enhance json detect

- .travis.yml
- Classes/FLEX.h
- Classes/Info.plist
- FLEX.xcodeproj/project.pbxproj
- FLEX.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- FLEX.xcodeproj/xcshareddata/xcschemes/FLEX.xcscheme
- FLEX.xcworkspace/contents.xcworkspacedata
- FLEX/FLEX.xcodeproj/project.pbxproj
- FLEX/FLEX.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- README.md
- Creates a root-level framework project that builds FLEX.framework
- Adds FLEX shared scheme
- Creates a root .xcworkspace to contain both the framework and example projects
- Updates `.travis.yml` to build both framework and example project
- Declares [Carthage](https://github.com/Carthage/Carthage) compatability in README
> Add framework support

- Classes/ExplorerToolbar/FLEXManager.h
- Classes/ExplorerToolbar/FLEXManager.m
Not required but may be useful since I typically manually do this with my tap gesture handlers. If you feel it's not necessary, feel free to reject this.
> Convenience method to show/hide explorer depending on current isHidden

- Classes/ExplorerToolbar/FLEXExplorerViewController.m
**If always dismiss first before present, then the property `previousKeyWindow` and `previousStatusBarStyle` will be not effective.**
`previousStatusBarStyle` for example:
1. original: white color
2. FLEX presented: black color
3. FLEX dismissed: still black color(`previousStatusBarStyle` lose effectiveness)
> - (void)toggle***Tool - It is not necessary to 'dismiss' when 'present'

- Classes/ObjectExplorers/FLEXViewExplorerViewController.m
- Classes/Utility/FLEXUtility.h
- Classes/Utility/FLEXUtility.m
This is more of a convenience thing in most cases. It does become quite useful when debugging parent and child view controllers and is quite helpful (personally) when messing with apps and injecting FLEX using Cydia Substrate. `_viewControllerForAncestor` is quite an old method and has been around since [iOS 4.2 (November 2010)](https://github.com/nst/iOS-Runtime-Headers/blob/4.2/Frameworks/UIKit.framework/UIView.h#L279) so it can be assumed that it is as safe `_viewDelegate` which was introduced in 4.0, I believe. It is, however, more robust in that the view controller can be determined from *any* view contained within a given view controller.
I left the old method as is, even though this new method should be a suitable replacement. I'll leave such changes up to the main contributors' …
> *Added the ability to determine a UIView's view controller without selection the view controller's view delegate.

- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXRealmDatabaseManager.m
Sorry about this! It appears a bug involving Realm nullability slipped through the cracks!
This PR adds a small check to ensure properties return from a Realm object are not nil, and substitutes an `NSNull` instance if it is to ensure the data is still valid when passed to an `NSArray` down the line.
> Added handling for nil Realm property values

- Classes/GlobalStateExplorers/FLEXInstancesTableViewController.m
when the number of objects changed frequently, may be will  crash that add wrong thing to instances
> fix crash when object malloc_size no greater than zero

- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXRealmDatabaseManager.m
- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXRealmDefines.h
Following the latest trends in Swift, Realm made the decision to deprecate using strings for file paths in its API in favour of `NSURL`. As of the latest version of Realm, 0.103.0, the deprecated `path` property was completely removed.
As reported in https://github.com/Flipboard/FLEX/issues/127, this pull request updates the integration of Realm in FLEX to use the new NSURL value for file paths.
> Replaced deprecated 'path' property in Realm configuration

- Classes/GlobalStateExplorers/FLEXClassesTableViewController.m
- Classes/GlobalStateExplorers/FLEXLibrariesTableViewController.m
- Classes/Utility/FLEXRuntimeUtility.m
- Classes/Utility/FLEXUtility.m
Added a way to jump to a specific class from the System Libraries tab,
since it is sometimes difficult to find a class if you don’t know which
bundle it’s in.
Also fixed a crash in the second commit. Whoever wrote `[FLEXRuntimeUtility valueForIvar:onObject:]` was checking `strcmp(name, "isa") != 0` when I think they intended to write `strcmp(name, "isa") == 0`, so I corrected that.
> Search for a specific class

- Classes/Network/PonyDebugger/FLEXNetworkObserver.m
`URLSession:task:willPerformHTTPRedirection:newRequest:completionHandler:`
`URLSession:dataTask:didReceiveResponse:completionHandler:`
The completion handler must be invoked If these delegates are implemented. Otherwise, the task will never finish.
> Fix method swizzling for NSURLSessionDelegate

- Classes/FLEXManager.h
- Classes/Manager/FLEXManager.m
- Classes/Network/FLEXNetworkRecorder.h
- Classes/Network/FLEXNetworkRecorder.m
Some network requests can be very noisy and congest the network recorder, such as analytics calls, or other calls you may not be interested in logged. This adds a simple filter to not log any of those requests.
> Add ability to filter out noisy network requests from being recorded

- Classes/Utility/FLEXKeyboardShortcutManager.m
Pressing Cmd+S in the Simulator normally just takes a screenshot, but in Xcode 9, it also triggers the default "s" keyboard shortcut which enables the FLEX Select tool. This is because the keyboard flags is ANDed with a logical NOT of UIKeyModifierShift instead of the bitwise inverse
> Fixed keyboard shortcuts in Xcode 9 simulator

- Classes/Network/FLEXNetworkTransactionTableViewCell.m
- Classes/Utility/FLEXUtility.h
- Classes/Utility/FLEXUtility.m
Currently only if there's an error on the transaction will the name be displayed in red. Showing 4xx or 5xx errors in red is helpful when looking at a glance for failed requests.
> Highlight request name in red if status code is a 4xx or 5xx

- Classes/Toolbar/FLEXExplorerToolbar.h
- Classes/Toolbar/FLEXExplorerToolbar.m
Exposes `FLEXExplorerToolbar.toolbarItems` as a public API so that others can more easily, safely, and reliably add their own items to the FLEX toolbar.
> Make FLEXExplorerToolbar more extensible

- Classes/Editing/ArgumentInputViews/FLEXArgumentInputView.m
- Classes/Utility/FLEXRuntimeUtility.m
- FLEX.xcodeproj/project.pbxproj
- FLEXTestsMethodsList/FLEXTestsMethodsList.m
- FLEXTestsMethodsList/Info.plist
In AAPLAppDelegate section app crashes while parsing selector `URLSession:downloadTask:didFinishDownloadingToURL: `
in iOS 10 number of arguments returned by `method_getNumberOfArguments()` is more than in `selectorComponents` array which causes crash on line.
`NSString *prettyComponent = [NSString stringWithFormat:@"%@:(%@) ", [selectorComponents objectAtIndex:argIndex - kFLEXNumberOfImplicitArgs], readableArgType];`
In iOS 9 `method_copyArgumentType()` returns NULL which causes crash on line
`NSString *readableArgType = [self readableTypeForEncoding:@(argType)];`
> Fix crash in FLEXRuntimeUtility

- .travis.yml
The `xctool` step failed in Travis CI. The reason is the `xctool` doesn't support `build` action anymore in the most recent version. See:
https://travis-ci.org/Flipboard/FLEX/jobs/317617537
https://github.com/travis-ci/docs-travis-ci-com/issues/1186
https://github.com/facebook/xctool
> Make Travis use xcodebuild (and xcpretty) instead of (deprecated) xctool

- Classes/ExplorerInterface/FLEXExplorerViewController.m
- Classes/Toolbar/FLEXExplorerToolbar.h
- Classes/Toolbar/FLEXExplorerToolbar.m
- Classes/Toolbar/FLEXToolbarItem.h
- Classes/Toolbar/FLEXToolbarItem.m
- Classes/Utility/FLEXUtility.h
Add `safeAreaInsets` handling to make sure the toolbar can only be laid out in `safeArea`.
I made sure that the Y-axis `safeArea` handling was done in `FLEXExplorerToolbar`, so that the background can occupy the fullwidth, and only the content was laid out in `safeArea`. In order to do so, the default semi-transparent background color was moved from `FLEXToolbarItem` to `FLEXExplorerToolbar`.
> Add iPhone X safe area handling to layout the toolbar correctly

- README.md
* Add Swift example
* Add explicit Carthage instructions
* Move some instructions around for parallel structure
Overall diff looks more complicated than it should be — please look at individual commits.
> Minor tweaks to the README

- Classes/Editing/ArgumentInputViews/FLEXArgumentInputStructView.m
- Classes/Editing/FLEXFieldEditorView.h
- Classes/Editing/FLEXFieldEditorView.m
- Classes/Editing/FLEXMethodCallingViewController.m
In https://github.com/Flipboard/FLEX/commit/a535f10d0c10176141f683b3aabf7c007ea6f443 I used `UIView` instead of `FLEXArgumentInputView`, which will cause compile issue with strict flags. So updating here to make sure everything works okay.
> Fix generics

- Classes/Network/PonyDebugger/FLEXNetworkObserver.h
Global variables that can be accessed from both C (or Objective-C) and
C++ (or Objective-C++) source files should be marked `extern "C"` when
in C++ mode (which is what `FOUNDATION_EXTERN` does), to ensure
consistent access across languages.
> Use FOUNDATION_EXTERN for global variable

- Classes/Utility/FLEXHeapEnumerator.m
We only need to enumerate the `DefaultMallocZone` zone to find objects in the Objc runtime.
---
I have [several outstanding PRs.](https://github.com/Flipboard/FLEX/pulls/NSExceptional) Most of them are very simple. I don't know who else to contact about this except to just mention it here and hope someone important sees it. @matrush, could you take a look at some of them?
> Fix heap enumeration crash

- Classes/GlobalStateExplorers/SystemLog/FLEXSystemLogMessage.m
- Classes/GlobalStateExplorers/SystemLog/FLEXSystemLogTableViewController.m
Currently, the system log screen just pulls in the entire list of messages from asl every time the list refreshes. Messages can sometimes expire quickly, which can be annoying when you're staring at one and it vanishes.
This new implementation will force log messages to persist until you dismiss the screen.
> System log will cache messages

- Classes/Utility/FLEXRuntimeUtility.m
When a user-invoked method call fails, FLEX presents a dialog informing you that it failed, but does not say why.
In practice, it is more useful to see the exception name and reason than the (potentially crazy long) object description.
> Reveal exception reason in dialog

- Classes/ExplorerInterface/FLEXExplorerViewController.h
- Classes/ExplorerInterface/FLEXExplorerViewController.m
Removes duplicate code related to presenting a view controller from the
FLEX window (usually triggered by a toolbar button).
This adds `-[FLEXExplorerViewController
presentOrDismissViewControllerFromToolbar:shouldDismiss:completion:]`
which also makes it easier for others to add their own toolbar buttons
to present some other kind of screen, or for FLEX itself to utilize
again in the future.
> Simplify view controller presentation code

- Classes/GlobalStateExplorers/FLEXInstancesTableViewController.m
- Classes/GlobalStateExplorers/FLEXObjectRef.h
- Classes/GlobalStateExplorers/FLEXObjectRef.m
- FLEX.xcodeproj/project.pbxproj
Often when looking through this area, it is time consuming to skip over objects you don't care about, such as auto-layout constraints when examining a UIView, among other things.
This makes it so that certain objects are grouped into their own sections. For now, Masonry and `NS*LayoutConstraint` objects are grouped together under **AutoLayout**, and `__NSObserver` and friends are grouped under **Trivial**. Other sections could easily be added.
[Here is what it looks like.](https://i.imgur.com/M19zkah.png)
@ryanolsonk Thoughts?
> Group similar "objects with ivars referencing this object"

- Classes/Editing/FLEXMethodCallingViewController.m
- Classes/ObjectExplorers/FLEXObjectExplorerViewController.m
- Classes/Utility/APPLE_LICENSE
- Classes/Utility/FLEXObjcInternal.h
- Classes/Utility/FLEXObjcInternal.mm
- Classes/Utility/FLEXRuntimeUtility.h
- Classes/Utility/FLEXRuntimeUtility.m
- FLEX.xcodeproj/project.pbxproj
Sometimes when interacting with lower level APIs like `_CFXNotificationObserverRegistration`, you encounter `void *` references that might actually be hiding references to Objective-C objects. It is rarely useful to call these methods in FLEX and look at the address inside the `NSValue` box provided by FLEX to view this value. Instead, it would be very convenient if we could somehow check if any arbitrary pointer is a pointer to an Objective-C object. And... we can!
When you call a method or access an ivar or property whose type is `void *` or `const void *`, FLEX will now automatically attempt to unbox it if it could be pointer to an object. In the same line of reasoning, this PR also unboxes C strings (`char *` or `const char *`) into `NSString`s. It also adds a sometimes helpful …
> Detect and unbox pointers to objects from void *

- Classes/Network/FLEXNetworkCurlLogger.m
Copying curl request should not be trimmed, as long curl requests are prime target for copying - manually building them is tedious, and they should be available regardless of the size
> Remove copied curl shortening

- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXMultiColumnTableView.m
Currently, if you use iPhone X or any iPhone with a notch to view database, the column names will be hidden under the navigation bar. This is because the safeArea is not respected. This commit contains a simple fix to that.
> Fix safeArea for database content view

- Classes/GlobalStateExplorers/FLEXFileBrowserTableViewController.m
- Classes/Utility/FLEXUtility.h
- Classes/Utility/FLEXUtility.m
Not all images have extension. For example in our application thumbnails and previews are saved in a file using as name base 64 handle without extension.
> Improve the detection of images

- Classes/GlobalStateExplorers/FLEXFileBrowserTableViewController.m
After FLEX 3.0, it's great that share single file is enabled while under FLEXFileBrowser.
For our case, it would be more convenient if it's able to share a directory.
---
For share directory, it's needed to use UIDocumentInteractionController instead of UIActivityViewController.
> It'll be more convenient to enable share directory while browsing files.

- Classes/Editing/FLEXFieldEditorViewController.m
- Classes/Network/FLEXNetworkHistoryTableViewController.m
- Classes/Network/FLEXNetworkTransactionDetailTableViewController.m
- Classes/Network/FLEXNetworkTransactionTableViewCell.m
- Classes/Toolbar/FLEXExplorerToolbar.m
- Classes/Utility/FLEXColor.h
- Classes/Utility/FLEXColor.m
- Classes/Utility/FLEXUtility.h
- Classes/Utility/FLEXUtility.m
- Classes/ViewHierarchy/FLEXHierarchyTableViewController.m
- Classes/ViewHierarchy/FLEXImagePreviewViewController.m
- FLEX.xcodeproj/project.pbxproj
This is an initial attempt to implement dark mode for FLEX.
In these two commits, we:
1. Move to FLEX semantic colors
2. For iOS13+, return a dynamic color provider for those semantic colors.
This dynamic color provider API is intentionally scoped only to handle light and dark mode (and not handling contrast, level, weight, etc) to keep things really simple.
This gets a bunch of the spots but there are still a few that still need updating, namely the icons.
> Initial Dark Mode work

- Classes/Editing/ArgumentInputViews/FLEXArgumentInputTextView.m
- Classes/Toolbar/FLEXExplorerToolbar.m
- Classes/Toolbar/FLEXToolbarItem.m
- Classes/Utility/FLEXColor.h
- Classes/Utility/FLEXColor.m
- Classes/Utility/FLEXResources.m
- Classes/Utility/FLEXUtility.m
In this PR, we add support for dark mode to the icons. It loads the icons as templates and uses tint color to support dark mode.
Also in this PR:
* Updated hierarchy indicator to support dark mode
* Reorganized `FLEXColor`
-----
Light:
Dark:
---
Light:
Dark:
> Dark Mode: Add support for icons

- Classes/Editing/ArgumentInputViews/FLEXArgumentInputObjectView.h
- Classes/Editing/ArgumentInputViews/FLEXArgumentInputObjectView.m
- Classes/Editing/ArgumentInputViews/FLEXArgumentInputTextView.h
- Classes/Editing/ArgumentInputViews/FLEXArgumentInputTextView.m
- Classes/Editing/ArgumentInputViews/FLEXArgumentInputView.h
- Classes/Editing/ArgumentInputViews/FLEXArgumentInputView.m
- Classes/Editing/ArgumentInputViews/FLEXArgumentInputViewFactory.m
- FLEX.xcodeproj/project.pbxproj
Currently, if argument type is `id`, there's no way to pass anything that can't be parsed from JSON.
This change adds the ability to select the type of argument to pass:
* Value - works the same as before, JSON from input string is parsed to NSDictionary/NSArray/NSString/etc.
* Address - uses object at the specified address, so you can call any method with object you previously created and populated to your preference
Here's a simple demonstration of how it works:
https://streamable.com/hcwo6
> Add ability to use object-by-address for method arguments with type id

- Classes/Utility/FLEXRuntimeUtility.m
For structures like this
```
typedef struct SomeStruct {
double a;
int b;
int c;
double d;
} SomeStruct;
```
Before this change, the `runningFieldOffset` for `a`, `b,` `c`, `d` will be `0, 8, 16, 24` respectively, which is wrong.
My understanding for `alignmentPadding` is we need to add it for the current running field only if the current field will overflow the `fieldAlignment`. So in this example the two ints `b` and `c` are actually stays in the same 8 bytes.
After this change, the `runningFieldOffset` for `a`, `b,` `c`, `d` will be `0, 8, 12, 16` respectively, which is correct.
I have tested using this for printing out the struct values and it is now correct.
> Fix struct field offset calculation when enumerating struct encoding

- Classes/Editing/ArgumentInputViews/FLEXArgumentInputNumberView.m
- Classes/Utility/FLEXRuntimeUtility.h
- Classes/Utility/FLEXRuntimeUtility.m
Add long double support in `FLEXRuntimeUtility`.
The only downside for this one is that the `NSNumber` doesn't support `long double`. However it was saying on iOS, the `sizeof(double) == sizeof(long double)`, so probably it's fine.
> Add long double support in FLEXRuntimeUtility

- Classes/Editing/ArgumentInputViews/FLEXArgumentInputViewFactory.m
- Classes/Utility/FLEXRuntimeUtility.h
- Classes/Utility/FLEXRuntimeUtility.m
Right now the struct parsing logic in FLEX doesn't support named fields.
A simple example like:
```
typedef struct TestSize {
double width;
double height;
} TestSize;
```
would be shown like this in FLEX:
The type encoding string is `{TestSize="width"d"height"d}`. However FLEX doesn't support the named fields in the parsing logic.
This PR tried to support the basic parsing support to make sure we can render both field name and field value properly. This would greatly help debugging C structs in general.
After the patch, this is how looks like for the same structs:
Most of the new code has inline comments.
Here are some references I looked at when implementing this:
- https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ObjCRuntimeGuide/Articles/ocrtTypeEncodings.html# …
> Add named struct field parsing support to fix the struct iVar issues

- Classes/GlobalStateExplorers/FileBrowser/FLEXFileBrowserTableViewController.m
The current implementation is deprecated, which limits the functionality
of the file browser.
> Add context menu to file browser in iOS 13.

- Classes/Core/FLEXScopeCarousel.m
- Classes/Core/FLEXTableViewController.h
- Classes/Core/FLEXTableViewController.m
- Classes/GlobalStateExplorers/Keychain/FLEXKeychainQuery.m
- Classes/ObjectExplorers/Views/FLEXTableView.m
- Classes/Utility/FLEXAlert.h
1. This block declaration is not a prototype
2. @available does not guard availability here; use if (@available) instead
We added FLEX manually to our project, we have the option `strict prototypes` enabled (YES) and we don't have in `Other warnings flags` the flag `-Wno-unsupported-availability-guard`
> Address "This block declaration is not a prototype" warning

- Classes/GlobalStateExplorers/SystemLog/FLEXOSLogController.m
The address of the messageText variable  is in the stack, when use disaptch_async, it will released.
> Fix stack memory being used in async block

- Classes/ExplorerInterface/FLEXExplorerViewController.m
Per Apple's documentation (https://developer.apple.com/documentation/uikit/uicontentcontainer/1621466-viewwilltransitiontosize) if you override this method in your custom view controller, always call super at some point in your implementation so that UIKit can forward the size change message appropriately.
This commit adds the call to super as required.
> Call super in viewWillTransitionToSize:withTransitionCoordinator:

- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXDatabaseManager.h
- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXRealmDatabaseManager.m
- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXSQLResult.h
- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXSQLResult.m
- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXSQLiteDatabaseManager.m
- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableContentViewController.h
- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableContentViewController.m
- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableListViewController.m
- FLEX.xcodeproj/project.pbxproj
Added ability to run execution and selection sql queries during sqlite db exploration.
> Added ability to run sql queries on sqlite files

- Classes/GlobalStateExplorers/SystemLog/FLEXSystemLogViewController.m
- Classes/Utility/Runtime/Objc/FLEXRuntimeSafety.m
Several functions are not marked as static and it will report missing prototypes warning and failed to build if `-Wmissing-prototypes` flag is on.
Also fixed an issue with `-Wmissing-braces` flag on.
> Make several functions static to avoid warning

- Classes/Manager/FLEXManager+Networking.m
Dispatch JSON response registration to main queue in `FLEXManager+Networking`
Issue introduced in 740daab55b42dfc7afeb5adc936fc36bc91f0ff8
The `load` call can happen in any thread but the `setCustomViewerForContentType` only works on main thread.
> Dispatch JSON response registration to main queue in FLEXManager+Networking

- README.md
It seems this has been changed from version 3.0 to 4.0, and you now access the singleton in Swift with `.shared` rather than `.shared()`. This reflects that change.
> Update README to use the current Swift `.shared`

- Classes/Utility/Categories/NSObject+FLEX_Reflection.h
- Classes/Utility/FLEXHeapEnumerator.m
- Classes/Utility/Runtime/Objc/FLEXObjcInternal.h
- Classes/Utility/Runtime/Objc/FLEXObjcInternal.mm
- Classes/Utility/Runtime/Objc/FLEXTypeEncodingParser.m
- Classes/Utility/Runtime/Objc/Reflection/FLEXMethod.m
This was previously discussed here: https://github.com/NSExceptional/FLEXing/issues/7
This solution seems to work 100% of the time, so I am assuming that locking and unlocking the zones is no longer needed on arm64e. It might be a good idea to confirm it however.
(Only applies for apps that have an arm64e slice, arm64 apps running on an arm64e device are not affected)
> Fix heap enumeration on arm64e devices

- Classes/GlobalStateExplorers/FileBrowser/FLEXFileBrowserController.m
I have problem when compiling this, and I think others may also have.
> Use __typeof instead of typeof. This is because both __typeof and typeof are extensions to C, but typeof is only enabled in Clang when the language is a GNUXX variant of C, but not for CXX.
https://stackoverflow.com/questions/32145326/weak-typeofself-weakself-self-expected-at-end-of-declaration/32145709#32145709
> use __typeof instead of typeof to compile for Cxx instead of GNUxx

- Classes/Utility/Runtime/Objc/FLEXObjcInternal.h
- Classes/Utility/Runtime/Objc/FLEXObjcInternal.mm
- Classes/Utility/Runtime/Objc/Reflection/FLEXIvar.m
Remove redundant `FLEXPointerIsTaggedPointer` function.
This caused build failure on my local checkout, the reason is that the function `FLEXPointerIsTaggedPointer` doesn't have a definition.
Since we already have the macro, we don't need this function. I just did a rename of the macro instead.
This was added in https://github.com/Flipboard/FLEX/commit/5d919eb3290762cf37f43a7eca729307e3bcfad2
> Remove redundant FLEXPointerIsTaggedPointer function

- Classes/GlobalStateExplorers/FLEXObjectListViewController.m
- Classes/ObjectExplorers/Sections/FLEXMutableListSection.m
- Classes/ObjectExplorers/Sections/Shortcuts/FLEXBundleShortcuts.m
Remove retain cycles from `selectionHandler` in several files.
These self were retained by the blocks `selectionHandler`, so we should use `weakSelf` and `strongSelf` instead.
> Remove retain cycles from selectionHandler in several files

- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableContentViewController.m
With FLEX 4.0, there is no ability to copy the db values from the DB browser. Before we improve this experience, let's add a quick copy action for now.
Demo:
>  Add copy action for database browser row selection alert

- Classes/GlobalStateExplorers/Globals/FLEXGlobalsViewController.h
- Classes/GlobalStateExplorers/Globals/FLEXGlobalsViewController.m
I find myself using the custom additions much more frequent than built actions. I believe this is true to a lot of others as well. So this PR tries to move them to the top so they are more accessible.
> Move custom additions to the top

- Classes/Utility/Runtime/Objc/Reflection/FLEXIvar.m
- Classes/Utility/Runtime/Objc/Reflection/FLEXProperty.m
Add better debugging message for `FLEXProperty` and `FLEXIvar`.
When the assertion failed, we want to know which class and which name are the problematic combinations.
> Add better debugging message for FLEXProperty and FLEXIvar

- Classes/ObjectExplorers/Sections/Shortcuts/FLEXShortcutsFactory+Defaults.m
> Add sharedApplication property at runtime for iOS 9

- Classes/Manager/FLEXManager+Extensibility.m
- Classes/Utility/Keyboard/FLEXKeyboardShortcutManager.h
- Classes/Utility/Keyboard/FLEXKeyboardShortcutManager.m
If the app adds custom keyboard shortcuts before FLEX sets default, the defaults will override the custom keys. For example, we use "t" to open our internal test settings (not FLEX), but that broke recently. Specifically, `[FLEXManager registerDefaultSimulatorShortcuts]` gets called after a `dispatch_async`, which gives the app enough time to register before.
When setting the default FLEX keys, lets not allow overrides. This way, if the app sets custom keys at any time (event at `+load`), the app custom keys get the priority.
> Fix keyboard shortcut registration

- Classes/Network/PonyDebugger/FLEXNetworkObserver.m
baseResumeClass name changed on iOS 14. In iOS 14 resume lives in NSURLSessionTask.
> Fix #446, baseResumeClass name for iOS14+

- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXSQLiteDatabaseManager.m
From internal crash stack trace, we are seeing:
```
Thread #0 Crashed:
0 CoreFoundation 0x18abf0300 __exceptionPreprocess + 228
1 libobjc.A.dylib 0x18a904c18 objc_exception_throw + 56
2 CoreFoundation 0x18aaed1f4 +[NSException raise:format:arguments:] + 96
3 Foundation 0x18af31994 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 128
4 NotInCore 0x10a2826fc -[FLEXMutableListSection setList:] (FLEXMutableListSection.m:49)
5 NotInCore 0x10a2825b4 -[FLEXMutableListSection initWithList:configurationBlock:filterMatcher:] (FLEXMutableListSection.m:33)
6 NotInCore 0x10a23b120 __cmp_gen_1f118 (Something else)
7 NotInCore 0x10a282c20 +[FLEXMutableListSection list:cellConfiguration:filterMatcher:] (FLEXMutableListSection.m:23)
8 NotInCore 0x10a248824 __cmp_gen_2c814 …
```
> Return empty array when the rows are nil in FLEXSQLResult

- Classes/Utility/Categories/UIBarButtonItem+FLEX.m
Hi,
There is a crash when you open Network History. Method unrecognized `flex_withTintColor`. I discovered that naming is incorrect in header and implementation (.m).
`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIBarButtonItem flex_withTintColor:]: unrecognized selector sent to instance 0x7fafcfe6d1f0'`
Please, consider this MR. 
Thanks for your work!
> Fix crash on `flex_withTintColor`

- Classes/ObjectExplorers/Sections/Shortcuts/FLEXLayerShortcuts.m
- Classes/ObjectExplorers/Sections/Shortcuts/FLEXViewShortcuts.m
This issue was introduced in https://github.com/FLEXTool/FLEX/commit/547bfbaec0c0910ee4c135722ff02c27d93826b6, there is a `!` missed in the boolean check, so fixing it here.
I also consolidated some logic around this, also apply the same thing to the `CALayer` as well.
> Fix view controller preview image issue

- Classes/ExplorerInterface/FLEXExplorerViewController.m
- Classes/Utility/FLEXResources.h
- Classes/Utility/FLEXResources.m
- Classes/ViewHierarchy/FLEXImagePreviewViewController.m
The default pattern background doesn't work well for some of the transparent images, adding this tap to toggle gesture can greatly improve the usability.
The 3 colors combination should work pretty well for most of the cases.
> Add ability to toggle background colors for image previews

- Classes/Core/Controllers/FLEXNavigationController.m
Navigation bar buttons didn't work on iOS 11-12. The bug was reproduced only on a real device.
Tested on:
- iPhone 6 Plus, iOS 11.0.3
- iPhone 11 Pro, iOS 14.2
> Fix navbar buttons tap handling

- Classes/GlobalStateExplorers/FLEXObjectListViewController.m
Fix build issue caused by changes in `FLEXObjectListViewController`.
Some changes were added in https://github.com/FLEXTool/FLEX/commit/e63ea4bbfff4200e4d371b1fd86448975162898d, it works fine by default, but if some advanced compile flags were enabled, it will start failing.
So here we added the missing `static` descriptor and removed an unused function.
> Fix a build issue caused by changes in FLEXObjectListViewController

- Classes/Core/Controllers/FLEXNavigationController.m
When I use swipe-to-back gesture, the toolbar does not appear, but when I use the Back button, the toolbar appears (see video).
Pull request fixes this issue. Tapping the navigation bar (not including the controls) still shows the toolbar.
https://user-images.githubusercontent.com/22199708/110830399-3a5a9c00-82aa-11eb-90b4-5e9f157c8e55.MP4
> Don't show toolbar by tap on UIControl in UINavigationBar

- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXSQLiteDatabaseManager.m
Sqlite is often smart enough to not need quotes for identifiers, unless you want to use a keyword as a name. Then you need to quote it
https://www.sqlite.org/lang_keywords.html
Fixes #524
> Fix: Correctly quote table names

- Classes/GlobalStateExplorers/Keychain/FLEXKeychain.h
- Classes/GlobalStateExplorers/Keychain/FLEXKeychain.m
- Classes/GlobalStateExplorers/Keychain/FLEXKeychainViewController.m
As the title says. This piece of information is useful especially when debugging keychain data sharing between same-vendor apps or extensions.
> Display access group for keychain items

- Classes/Manager/FLEXManager.m
- Example/FLEXample/Supporting Files/Info.plist
When showing FLEX for the first time when the app is in split view (not in full screen) on iPad, FLEX will layout itself as the width of the whole screen:
(you may need to disabled the auto-opening FLEX code in `SceneDelegate.swift` in FLEXample project to reproduce this case)
This pr fixed this bug.
BTW, I'm not familiar with objc, so feel free to edit this pr if needed~
> Fixed the frame error when showing FLEX for the first time

- FLEX.xcodeproj/project.pbxproj
- change wrong public headers to private to fix warning using xcframework
- set install path as default
these changes will make FLEX packaged to xcframework better.
> fix public header warnings & install path for xcframework compatible with SPM

- Classes/GlobalStateExplorers/FileBrowser/FLEXFileBrowserController.m
Fixing the crash on sharing single file on iPad by setting the `shareSheet.popoverPresentationController.sourceView = sender`
error:
```swift
Terminating app due to uncaught exception 'NSGenericException', 
reason: 'UIPopoverPresentationController (<UIPopoverPresentationController: 0x7fc18ec54320>) should have a non-nil sourceView or barButtonItem set before the presentation occurs.'
```
> Fix crash when sharing single file on iPad

- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXDBQueryRowCell.h
- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXDBQueryRowCell.m
- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXMultiColumnTableView.h
- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXMultiColumnTableView.m
- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableColumnHeader.m
- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableContentViewController.m
Show full text for DB browser column headers.
Currently the header has a fixed width of 120pts. This isn't ideal as some of the columns will have names that cannot fit, and user cannot expand its width like Excel or Google Spreadsheet.
So in this PR I'm trying to use `MAX(120pt, sizeThatFits)` as the width of the header and content, so that they can be consumed in a better way.
> Show full text for DB browser column headers

- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableContentViewController.h
- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableContentViewController.m
- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableListViewController.m
**Problem:**
At some cases, we need to delete all records in a table to replicate a specific scenario. The only way to do this right now is to run SQL query from tables list. 
**This PR:**
Adds a toolbar button when you open a table to delete all records. Now it's easier than writing a SQL query.
WIP: Add an option to delete a specific row.
https://user-images.githubusercontent.com/1477248/125656863-b51e1af1-7461-4265-bbd5-d42792535572.mp4
> Add a toolbar button to delete all records in a table

- Classes/ObjectExplorers/Sections/Shortcuts/FLEXShortcutsFactory+Defaults.m
Add availability check for iOS 11+ SFSafariViewController properties.
The [`configuration`](https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller/configuration) and [`dismissButtonStyle`](https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller/dismissButtonStyle) properties are both iOS 11+ only. They were added in https://github.com/FLEXTool/FLEX/commit/bbaa85bdbffe2b42cf06cbda43f5ec6393ce99a9. Let's add availability check to make sure there is no runtime assertion on certain OS versions.
The error I got was:
```
NSInternalInconsistencyException at +[FLEXProperty named:onClass:] in FLEXProperty.m:49: Cannot find property with name configuration on class SFSafariViewController
```
> Add availability check for iOS 11+ SFSafariViewController properties

- FLEX.xcodeproj/project.pbxproj
This reverts some changes in fix #514 that breaks FLEX when it is built with Xcode 12 and 13. Since this change I was getting when running an app linked to FLEX.framework.
```
dyld[4587]: Library not loaded: /Library/Frameworks/FLEX.framework/FLEX
Referenced from: /private/var/containers/Bundle/Application/redacted/redacted.app/redacted
Reason: tried: '/Library/Frameworks/FLEX.framework/FLEX' (no such file), '/System/Library/Frameworks/FLEX.framework/FLEX' (no such file)
Library not loaded: /Library/Frameworks/FLEX.framework/FLEX
Referenced from: /private/var/containers/Bundle/Application//redacted/redacted.app/redacted
Reason: tried: '/Library/Frameworks/FLEX.framework/FLEX' (no such file), '/System/Library/Frameworks/FLEX.framework/FLEX' (no such file)
(lldb) 
```
> Update project.pbxproj to fix crash on launch.

- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableContentViewController.m
Adding an option to copy a row in DB as comma separated values. This will make it easier to insert a row in DB using the feature implemented in #575 
https://user-images.githubusercontent.com/1477248/143222614-fd42d2e4-d4a5-4bb7-97ff-ca3c76c90edd.mov
> Add option to copy row as CSV

- Classes/Network/FLEXFirebaseTransaction.mm
- Classes/Network/FLEXNetworkTransaction.h
Mark some firebase related functions as static to avoid warnings.
This function is not used externally, and shows warnings when compile. Let's fix it.
```
stderr: FLEX/src/Classes/Network/FLEXFirebaseTransaction.mm:52:29: error: no previous prototype for function 'FIRDirectionFromRequestType' [-Werror,-Wmissing-prototypes]
FLEXFIRTransactionDirection FIRDirectionFromRequestType(FLEXFIRRequestType type) {
^
FLEX/src/Classes/Network/FLEXFirebaseTransaction.mm:52:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
FLEXFIRTransactionDirection FIRDirectionFromRequestType(FLEXFIRRequestType type) {
^
static
1 error generated.
```
> Mark some firebase related functions as static to avoid warnings

- Classes/Core/Controllers/FLEXNavigationController.m
It's an annoying warning and caused my local build to fail when treating warning as error. Let's just fix it.
> Fix -Wobjc-signed-char-bool-implicit-int-conversion issue

- Classes/ObjectExplorers/Sections/Shortcuts/FLEXShortcutsFactory+Defaults.m
- Example/FLEXample/App/CommitListViewController.m
Can see accessibilityIdentifier and accessibilityLabel in view Shortcuts section.
Useful for Accessibility debugging and finding UI in code.
> Add accessibilityIdentifier and accessibilityLabel to views properties

- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableContentViewController.m
The row array could always be empty `@[]` for an empty db instead of `nil`. We shouldn't check `.count` which will cause crashes.
> Check rowIDs instead of rowIDs.count when validating input

- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXSQLResult.m
- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXSQLiteDatabaseManager.m
Add fallback column query support when `PRAGMA table_info` is not working.
This is my attempt to fix #554, which is a less intrusive way comparing to #555. More detail about the bug itself can be found in #555.
The change I did here are two parts:
1. Fallback to use a slightly hackier solution when the `PRAGMA table_info` is not working.
2. Do not consider 0 row result as an `UPDATE/INSERT/DELETE`, it's common that our result has 0 rows.
> Add fallback column query support when PRAGMA table_info is not working

- Classes/Network/FLEXMITMDataSource.m
There is a crash caused by this because of race condition. Here we can simply make a copy of the transaction and it will be used and released properly even within the block.
The crash is both reported in #574 as well as my internal crash log:
```
Thread #32 Crashed:
0 libobjc.A.dylib 0x198de1540 objc_msgSend + 0x20
1 FLEXFramework 0x110104c00 __40-[FLEXMITMDataSource filter:completion:]_block_invoke (FLEXMITMDataSource.m:57)
2 FLEXFramework 0x110105110 __56-[FLEXMITMDataSource onBackgroundQueue:thenOnMainQueue:]_block_invoke (FLEXMITMDataSource.m:99)
3 libdispatch.dylib 0x180215920 _dispatch_call_block_and_release + 0x1c
4 libdispatch.dylib 0x18021766c _dispatch_client_callout + 0x10
5 libdispatch.dylib 0x18021a794 _dispatch_queue_override_invoke + 0x314
6 libdispatch.dylib 0x180228ddc …
```
> Fix self.allTransactions race condition in FLEXMITMDataSource

- Classes/FLEX-Categories.h
- Classes/FLEX-Core.h
- Classes/FLEX-ObjectExploring.h
- Classes/FLEX-Runtime.h
- Classes/FLEX.h
- FLEX.xcodeproj/project.pbxproj
- Fix compile error: add FLEXFirebaseTransaction.mm into project which was broken in commit: d2e0db87731fd16c90462625a8fdfad642611b00
- Fix the root cause for the PR: https://github.com/FLEXTool/FLEX/pull/547
DYLIB_INSTALL_NAME_BASE should keep @rpath when INSTALL_PATH=$(LOCAL_LIBRARY_DIR)/Frameworks
- Fix #import <> error using Carthage, "" instead.
- Fix some warnings caused by headers visibility.
- SPM, Carthage and Cocoapods test passed.
> Fix compile errors and warnings

- Classes/GlobalStateExplorers/SystemLog/FLEXSystemLogViewController.m
I encountered 2 problems in the process of using Flex System Log
1. After entering the System Log page, it's need to scroll to top and show the SearchBar. I think it would be better to keep it pinned.
2. handleUpdateWithNewMessages, a function that accepts new messages, is called a lot, but the messages are not filtered in this function, and course some problem. For example, activate the SearchBar and enter the filter text, then click the search button on keyboard, and then the keyboard exits. Received new message, but after call ```[self reloadData]```, all messages are unfiltered.
> video
https://user-images.githubusercontent.com/2723525/162410523-ea8b10af-6e9d-43d9-bab9-c8c2bbb4d5c8.mp4
> [System Log] Always show SearchBar & Alway filter new log if filterText is not empty

- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableContentViewController.m
- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableRowDataViewController.h
- Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableRowDataViewController.m
- Classes/GlobalStateExplorers/FLEXObjectListViewController.m
- Classes/ObjectExplorers/Sections/FLEXMutableListSection.h
- FLEX.xcodeproj/project.pbxproj
Introduce `FLEXTableRowDataViewController` to view table row data.
Currently since FLEX 4.0, if you tap on a specific field on a db cell, the whole row's data will be aggregated and we only show the result in an alert view. This is not ideal since often times one wants to copy a certain value from the cell in order to achieve something else.
So I introduced a new view controller to focus on a certain row to view the data in a better way.
Demos:
> Introduce FLEXTableRowDataViewController to view table row data

- Classes/Utility/Runtime/Objc/FLEXSwiftInternal.mm
Fix `-Wobjc-signed-char-bool-implicit-int-conversion` for `FLEXSwiftInternal`
Fixing this trace. If you have the `-Wobjc-signed-char-bool-implicit-int-conversion` enabled and `-Werror` enabled this will fail to build.
```
[CONTEXT] 
stderr: FLEX/Classes/Utility/Runtime/Objc/FLEXSwiftInternal.mm:88:9: error: implicit conversion from integral type 'unsigned long' to 'BOOL' [-Werror,-Wobjc-signed-char-bool-implicit-int-conversion]
[CONTEXT]         return rodata & FAST_IS_SWIFT_STABLE;
[CONTEXT]         ^
[CONTEXT]                (                            ) ? YES : NO
```
See more context here: https://stackoverflow.com/questions/65302104/how-to-enable-the-compiler-option-wobjc-signed-char-bool-implicit-int-conversio
> Fix -Wobjc-signed-char-bool-implicit-int-conversion for FLEXSwiftInternal

- Classes/ExplorerInterface/FLEXExplorerViewController.m
> fixup: Fix crash on iOS 16 and above

- Package.swift
Hi,
I would like to contribute fixing a recent warning.
The new Xcode 14 uses iOS SDK 11.0 as base, and compiling in this Xcode shows a warning.
Handle this restriction relying on swift version.
Regards and comments welcomed
> Xcode 14 - Warnings related to iOS 11 support (Swift Package Manager)

- Classes/Network/PonyDebugger/FLEXNetworkObserver.m
- Example/FLEXample/MiscNetworkRequests.m
Send message hook was changing original completion instead of wrapping it in a hook.
Similar hook already exists for receivemessage functionality, but it was not working for send-message, original completion was never called.
Adjusted code to create a new completionHook which records the information and then original completion block.
I also updated API-Key for piesocket and added a message after sending message, to make sure that completion is being called and at least success/failure message is logged.
> Fixed issue where websocket hook did not call original completion

- Classes/Network/FLEXNetworkRecorder.m
Small bug introduced in https://github.com/FLEXTool/FLEX/commit/b45c655ba2432f827d6b07faf9844a9111c51716
> Use queue instead of self.queue in FLEXNetworkRecorder.m

- README.md
Fixes https://github.com/FLEXTool/FLEX/commit/4f1ff7784d2fd7cbafce0d7cfb3af373a1afebe5#r84796860.
I chose to use `FLEX*` instead of `FLEX.*`, because it's even less error-prone, and it's consistent with https://github.com/FLEXTool/FLEX/blob/master/README.md#flex-files-added-manually-to-a-project.
> Fix error-prone FLEX exclusion from release instruction

- Classes/Network/PonyDebugger/FLEXNetworkObserver.m
This PR fixes the issue discussed in #568 
[This comment describes the issue in detail](https://github.com/FLEXTool/FLEX/issues/568#issuecomment-1141015572) and the changes in this MR helps ensure that the accumulator is never null.
> Fix "response body not in cache" issue on iOS 15+

- Classes/ObjectExplorers/Sections/Shortcuts/FLEXWindowShortcuts.m
In some locales where the decimal separator isn't a dot, the animation speed editor doesn't work with decimal value.
The `UIKeyboardTypeDecimalPad` keyboard has a comma key in French, but it is then parsed expecting a dot for the decimal.
I changed it to use `NSNumberFormatter`, which is locale-aware, and correctly expects a comma as a decimal separator in such languages.
> Fix animation speed modification in other locales

- Classes/Network/PonyDebugger/FLEXNetworkObserver.m
the crash happened after I used FLEX and Firestore in my app, the root cause for it is trying to set error in Orig block and the
error value is nil so we need to check on it first
> Fix EXC_BAD_ACCESS in FLEXNetworkObserver

- Classes/Utility/Runtime/Objc/Reflection/FLEXProtocol.m
On iOS 10 and above, `requiredProperties` and `optionalProperties` are preferred over the deprecated `properties`.
Since FLEX only requires iOS 9 and above, a fallback is provided for older versions.
> Use requiredProperties and optionalProperties in debug description

- Package.swift
This PR fixes a Xcode 15 SPM warning related to iOS 12 support, which is the minimum version supported.
> Fix Xcode 15 SPM warning related to iOS 12 support

- Classes/Network/PonyDebugger/FLEXNetworkObserver.m
AVAggregateAssetDownloadTask deeply does not like to be looked at. Accessing -currentRequest or -originalRequest will crash. Do not try to observe these.
Fixes #276
> Ignore AVAssetDownloadURLSession to avoid crashing. (FLEXTool#276)

- Classes/Network/FLEXNetworkCurlLogger.m
If body is not a UTF8 text - encode body as base64 and feed it into cuRL using pipeline of shell commands.
> Handle HTTP body which is not a UTF8 text

- Classes/ViewHierarchy/SnapshotExplorer/FHSView.m
```
*** Assertion failure in void _UIGraphicsBeginImageContextWithOptions(CGSize, BOOL, CGFloat, BOOL)(),
UIGraphics.m:410
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException',
reason: 'UIGraphicsBeginImageContext() failed to allocate CGBitampContext:
size={0, 0}, scale=3.000000, bitmapInfo=0x2002.
Use UIGraphicsImageRenderer to avoid this assert.'
libc++abi: terminating due to uncaught exception of type NSException
```
> Fix crash when opening view debug hierarchy

- Classes/Core/Controllers/FLEXTableViewController.m
- Classes/Editing/ArgumentInputViews/FLEXArgumentInputFontsPickerView.m
- Classes/Utility/Keyboard/FLEXKeyboardHelpViewController.m
iOS 9 is nine years old, and by dropping support we can clean up several APIs which were deprecated in iOS 10.
I've also cleaned up a couple other deprecated APIs:
- dimsBackgroundDuringPresentation is deprecated in iOS 12 in favor of obscuresBackgroundDuringPresentation which is available starting in iOS 9.1
- UIBarStyleBlackOpaque is deprecated in iOS 13 in favor of UIBarStyleBlack which is available from iOS 3
- showsSelectionIndicator is deprecated in iOS 13. According to the deprecation warning, "This property has no effect on iOS 7 and later" so we can safely remove it.
As a follow up question: is there interest in raising the min iOS version even further? There are lots of `@available` checks for iOS 11 and 13 as well.
> Clean up deprecated APIs

- SM/Surfile
Using [Surmagic](https://github.com/gurhub/surmagic), we can simplify the process of building xcframework that helps to decrease compile time for this pod.
This PR adds default SM config file so just need to run
```zsh
surmagic xcf
```
to get your pre-built xcframework
We can feel it is easier to add `binary-version` to Release assets rather than just compress the snapshots of source code at release time
> Add Surmagic surfile

- Classes/Network/FLEXHTTPTransactionDetailController.m
- Classes/Network/FLEXNetworkCurlLogger.m
- Classes/Utility/FLEXUtility.h
- Classes/Utility/FLEXUtility.m
Issue:
- When tapping the "Copy curl" button the cURL string has missing request body (it shows as null) when the content is compressed (gzip, deflate)
Fix:
- I realized that the library already has a way to decode compressed payloads since the request body shows fine in the UI. So I just moved the check for `Content-Encoding` to `FLEXUtility` to reuse in the `FLEXNetworkCurlLogger` and call the inflate method from `FLEXUtility` when necessary.
> Fix cURL null payload for compressed HTTP bodies

- Classes/ViewHierarchy/SnapshotExplorer/FHSView.m
Addressing issue #716: Attempting to enter the View Hierarchy Snapshot Explorer leads to a SpringBoard crash on iOS 18.2 (simulator) when using an iPhone 16 device.
This change introduces a helper method for hiding/unhiding views in `FHSView.m`, `_setHidden:forView:`, which handles potential exceptions raised when interacting with some classes.
For more details about the crash: https://github.com/FLEXTool/FLEX/issues/716
> fix: snapshot explorer crashes springboard on some iOS 18 devices
