FLEXTool/FLEX

Classes/Explorer Toolbar/FLEXManager.h
Classes/Global State Explorers/FLEXFileBrowserFileOperationController.m
Classes/Network/FLEXNetworkTransaction.h
Classes/Network/PonyDebugger/FLEXNetworkObserver.h

this is useful if this is being added to a dynamic framework

fix some imports so we don't depend on pch file

---

Classes/ExplorerToolbar/FLEXExplorerViewController.m
Classes/GlobalStateExplorers/FLEXFileBrowserFileOperationController.m
Classes/Info.plist
Classes/Network/PonyDebugger/FLEXNetworkObserver.m
Example/UICatalog.xcodeproj/project.pbxproj
Example/UICatalog.xcodeproj/xcshareddata/xcschemes/UICatalog.xcscheme
Example/UICatalog/UICatalog-Info.plist
FLEX.xcodeproj/project.pbxproj
FLEX.xcodeproj/xcshareddata/xcschemes/FLEX.xcscheme

Addresses #73 and #74.
c250200 fixes the warning in Xcode 7 but introduces a warning in Xcode 6. I think that's livable given that the transition to Xcode 7 is imminent.
@tijoinc for review

Xcode 7 Cleanup

---

Classes/Network/PonyDebugger/FLEXNetworkObserver.m

Resolves https://github.com/Flipboard/FLEX/issues/73.

Remove unused typedef

---

Classes/GlobalStateExplorers/FLEXCookiesTableViewController.h
Classes/GlobalStateExplorers/FLEXCookiesTableViewController.m
Classes/GlobalStateExplorers/FLEXGlobalsTableViewController.m
Example/UICatalog.xcodeproj/project.pbxproj
FLEX.xcodeproj/project.pbxproj

Hi,
I've added a very small amount of code that allows for a very basic way of browsing shared cookie storage - something I found useful.
Rich

Add basic support for viewing shared HTTP cookie storage

---

Classes/GlobalStateExplorers/DatabaseBrowser/FLEXDatabaseManager.h
Classes/GlobalStateExplorers/DatabaseBrowser/FLEXDatabaseManager.m
Classes/GlobalStateExplorers/DatabaseBrowser/FLEXMultiColumnTableView.h
Classes/GlobalStateExplorers/DatabaseBrowser/FLEXMultiColumnTableView.m
Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableColumnHeader.h
Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableColumnHeader.m
Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableContentCell.h
Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableContentCell.m
Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableContentViewController.h
Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableContentViewController.m
Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableLeftCell.h
Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableLeftCell.m
Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableListViewController.h
Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableListViewController.m
Classes/GlobalStateExplorers/DatabaseBrowser/LICENSE
Classes/GlobalStateExplorers/FLEXFileBrowserTableViewController.m
Example/UICatalog.xcodeproj/project.pbxproj
FLEX.xcodeproj/project.pbxproj
README.md

Hi,
I've added a database browser for opening a .db file.
Sometimes, Some people may want to view SQLite databases on device.

Add a sqlite database browser

---

CONTRIBUTING.md
README.md

move to more permissive contribution doc.
@timonus @ryanolsonk

Add contributing stub

---

README.md

Oops! Something I clean forgot to include in my original PR. Sorry about that!
This PR updates the README, to both mention the `sqlite` extension for SQLite, as well as Realm now being a supported format. :)

Updated database features in README.

---

README.md

Hi!
I mostly use Carthage for my projects, and needed a way to properly exclude FLEX from release builds. I found one and added instructions to the readme file. This provides a more detailed answer to issue #131, which has been closed.
I did not include any screenshot since yours seem hosted on your own. Here is an example if you want to upload it with the others and update the readme file accordingly:
Thanks for considering this (small) contribution to your awesome project!
Best regards.

Add Carthage instructions for FLEX exclusion from release builds

---

Classes/ViewHierarchy/FLEXImagePreviewViewController.m

Hi, I've just replaced the original **Copy** button with an **Action** button in `FLEXImagePreviewViewController`, it behaves just like the **Photos** app, providing actions like "Save to Camera Roll", "AirDrop" and so on. I guess it's pretty handy.
I totally love this project, and hope to make it more powerful.

Add a convenient action button in FLEXImagePreviewViewController

---

Classes/FLEXManager.h
Classes/GlobalStateExplorers/DatabaseBrowser/FLEXSQLiteDatabaseManager.m

Add support for SQLCipher protected databases

---

Classes/GlobalStateExplorers/FLEXFileBrowserTableViewController.m

Although FLEX can open files directly for browsing, such as databases, plists, text files, and so on. But for a large number of text information files, although FLEX provides copy function, a lot of text is difficult to transfer from my mobile phone to my computer. 
For example, I use 'CocoaLumberjack' to record the user log. When the tester feedbacks the problem, I need to export the log file to the mac. However, FLEX currently does not have file sharing capabilities. I think the file sharing feature is a must for some developers. So, I hope FLEX can support it.

add share  action to FLEXFileBrowserTableViewController

---

Classes/ObjectExplorers/FLEXObjectExplorerViewController.m

Scopes now include:
- No inheritance (base class)
- Base class with parent attributes
- Base class with all inherited attributes, except NSObject
- NSObject attributes only
It is unusual that you need to see anything but the parent's attributes alongside those of the base class, and you especially rarely need to see NSObject attributes.
[Here's what it looks like.](https://i.imgur.com/sXMt7xT.png) The `+ Inherited` and `+ Parent` tabs hide depending on how far down the object is in the inheritance hierarchy (so, if it inherits directly from `NSObject`, the only other tab will be `NSObject`)

Additional object explorer scopes

---

Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableContentViewController.m

on an iPhoneX device, database UI（database field） don't show complete.
For more information , see attach file(two pictures)

iPhoneX database UI display is incomplete

---

Classes/GlobalStateExplorers/FLEXGlobalsTableViewController.m
Classes/ObjectExplorers/Controllers/FLEXGlobalsTableViewControllerEntry.h
Classes/ObjectExplorers/Controllers/FLEXGlobalsTableViewControllerEntry.m
Classes/Utility/FLEXObjcInternal.mm
Classes/Utility/FLEXUtility.h
Classes/Utility/FLEXUtility.m
Example/UICatalog.xcodeproj/project.pbxproj

* Add new item to FLEX menu - "Address Inspector"
* Allows inspecting/modifying objects at arbitrary memory addresses

Add address inspector

---

FLEX.podspec

for detail, see https://github.com/Flipboard/FLEX/issues/272

Fix missing system frameworks dependencies

---

Classes/GlobalStateExplorers/FLEXWebViewController.m
FLEX.podspec

Basically replacing the deprecated UIWebView with WKWebView.

Fix build errors when using UIKit for Mac (Project Catalyst)

---

Classes/Core/FLEXTableViewController.m

a small change to make Xcode 10 happy.

fix xcode 10 compiling issue;

---

Classes/FLEXManager.h
Classes/Manager/FLEXManager.m

Add support for new UIScene APIs

---

Classes/Manager/FLEXManager.m

Fix type cast error

---

Classes/Utility/FLEXRuntimeUtility.m

Fixed some minor issues found during debugging.

Fix issues in FLEXRuntimeUtility

---

Classes/Editing/ArgumentInputViews/FLEXArgumentInputStructView.m
Classes/Utility/FLEXRuntimeUtility.m

Add `CGVector` and `NSDirectionalEdgeInsets` support.
These are new common types. So following other examples to add support for them.

Add CGVector and NSDirectionalEdgeInsets support

---

Classes/Network/PonyDebugger/FLEXNetworkObserver.m

When using FLEX, my App may crash on a frequency of about one time per 1~2 days(I think it depends on how many network request we send).
I assume the crash is caused by part of the code of HTTPParser is not thread-safe, and invoke it asynchronously may cause double-free crash. So I manually ask for HTTPBody synchronously, make the HTTPParser parse the request and cache them in advance, before any possible asynchronous invoking.
1. Run our App with FLEX integrated
2. Make sure NSURLSession is hooked
3. It may take days to reproduce the crash

Fix crash during NSURLSession's resume

---

Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableListViewController.h
Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableListViewController.m

This Commit adds a Searchbar to Database Table Viewer Tables List.
For that it turns FLEXTableListViewController into a FLEXTableViewController sublcass, calls showSearchbar=YES and implements updateSearchResults

Add Searchbar to Database Table Viewer Tables List

---

Classes/GlobalStateExplorers/Keychain/FLEXKeychainTableViewController.m
Classes/ObjectExplorers/FLEXObjectExplorerFactory.m
Classes/Utility/Categories/UIPasteboard+FLEX.h
Classes/Utility/Categories/UIPasteboard+FLEX.m
FLEX.xcodeproj/project.pbxproj

fixed: Keychain crash while account is kind of NSData
fixed: FLEXGlobalsRowRootViewController is no respone

Fixed Bugs

---

Classes/GlobalStateExplorers/FileBrowser/FLEXFileBrowserController.m

In order to allow sorting the File Browser by Name or Creation Date, adding a Sort button to the toolbar:
The Sort button opens this Action Sheet:
Sort by name:
Sort by creation date:

Add sorting in File Browser

---

Classes/GlobalStateExplorers/DatabaseBrowser/FLEXRealmDatabaseManager.m

A very simple PR as the title suggest, this will sort Realm's DB table name alphabetically.

Sort Realm Table Name Alphabetically

---

Classes/GlobalStateExplorers/Keychain/FLEXKeychainViewController.m

Fix crashing when viewing keychain that may contains NSData.

Fix viewing keychain crash.

---

Classes/GlobalStateExplorers/DatabaseBrowser/FLEXDatabaseManager.h
Classes/GlobalStateExplorers/DatabaseBrowser/FLEXSQLiteDatabaseManager.m
Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableContentViewController.h
Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableContentViewController.m
Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableListViewController.m

Adding the option to delete a specific row. Due to the absence of knowledge of primary keys, I decided to use rowid in SQL to delete rows. Rowids will be injected along with rows and columns. 
This PR depends on #542 
https://user-images.githubusercontent.com/1477248/125669245-7f480303-7a94-4776-8bd7-317cc7035bf5.mp4

Option to delete a row

---

Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableListViewController.m

Fix realm database viewer crash

---

Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableContentViewController.m

Fixes #571.
See the screenshot after fix:

Remove unneeded edgesForExtendedLayout setting

---

Classes/GlobalStateExplorers/DatabaseBrowser/FLEXSQLiteDatabaseManager.m
Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableContentViewController.h
Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableContentViewController.m
Classes/GlobalStateExplorers/DatabaseBrowser/FLEXTableListViewController.m

Added a new toolbar button to insert a new row. Tapping on the button will show an alert to write the values as a comma separated string which will be added in an INSERT statement to be executed.
https://user-images.githubusercontent.com/1477248/143076971-3c2f2b93-85e2-4e4f-ab22-741ed05dc078.mp4

Adding an option to add a row in DB table

---

Classes/Headers/NSDateFormatter+FLEX.h

Fix Swift Package Manager integration

---

FLEX.podspec

Specify xcconfig settings in spec only for pod, not for consuming project.

Podspec: update xcconfig to pod_target_xcconfig

---

Classes/ExplorerInterface/FLEXExplorerViewController.m

Resolves #535 
Tested only on the Simulator, with Xcode 13.4.1

Fix for when the keyboard covers the Tool Bar

---

Classes/ObjectExplorers/FLEXObjectExplorer.m

[info]fix the name is nil cause crash

---

Classes/Network/PonyDebugger/FLEXNetworkObserver.m

Fix bug CRASH EXC_BAD_ACCESS  #691

[B, 691] fix EXC_BAD_ACCESS in FLEXNetworkObserver

---

Classes/GlobalStateExplorers/FileBrowser/FLEXFileBrowserController.m
Classes/GlobalStateExplorers/Keychain/FLEXKeychainQuery.m

Replacing the deprecated usages with their corresponding recommended APIs.

Migrate NSKeyedArchiver/NSKeyedUnarchiver deprecated APIs

---

Classes/Headers/FLEXFileBrowserController.h
FLEX.podspec
generate-spm-headers.sh

This allows to add custom menu item to browse application group container or other path of interest.
This is related to #668.

Make FLEXFileBrowserController public

---

Classes/Core/Controllers/FLEXTableViewController.m

fix: https://github.com/FLEXTool/FLEX/issues/672

Fix #672 misaligned UITableView row height
